/** Medical specialties list — synced with ai-scribe-web (dev branch) profile dropdown. */
export const SPECIALTIES = [
  "Adult Reconstructive Orthopedics",
  "Allergy",
  "Allergy/Immunology",
  "Anesthesiology",
  "Cardiology",
  "Cardiovascular Surgery",
  "Colon and Rectal Surgery",
  "Critical Care",
  "Dentistry",
  "Dermatology",
  "Diagnostic Radiology",
  "Emergency Medicine",
  "Endocrinology, Diabetes & Metabolism",
  "Endodontist",
  "Family Practice",
  "Foot and Ankle Orthopedics",
  "Gastroenterology",
  "General Dentistry",
  "General Practice",
  "Geriatric Medicine- IM",
  "Gynecologic Oncology",
  "Gynecology",
  "Hematology",
  "Hematology/Oncology",
  "Hospitalist",
  "Immunology",
  "Infectious Diseases",
  "Infertility",
  "Internal Medicine",
  "Interventional Cardiology",
  "Medical Oncology",
  "Neonatology",
  "Nephrology",
  "Neurological Surgery",
  "Neurology",
  "Nuclear Medicine",
  "Nutrition",
  "Obstetrics",
  "Obstetrics/Gynecology",
  "Occupational Medicine",
  "Ophthalmology",
  "Optometrist",
  "Oral and Maxillofacial Pathology",
  "Oral Surgery",
  "Orthodontics",
  "Otolaryngology",
  "Pain Medicine",
  "Pathology",
  "Pediatric Cardiology",
  "Pediatric Dermatology",
  "Pediatric Orthopaedic Surgery",
  "Pediatrics",
  "Pedodontist",
  "Periodontics",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgery",
  "Podiatry",
  "Prosthodontist",
  "Psychiatry",
  "Pulmonary Medicine",
  "Radiology",
  "Reproductive Endocrinology",
  "Rheumatology",
  "Spine Surgery",
  "Sports Medicine",
  "Surgery, General",
  "Surgical Oncology",
  "Urology",
  "Vascular Surgery",
  "Other",
] as const;
